sudo: required
language: generic

services:
 - docker

before_install:
  - docker build -t phhongphuc/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true phhongphuc/react-test npm test

after_success:
  - docker build -t phhongphuc/multi-client ./client
  - docker build -t phhongphuc/multi-nginx ./nginx
  - docker build -t phhongphuc/multi-server ./server
  - docker build -t phhongphuc/multi-worker ./worker

# Log in to the docker CLI 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Take those images and push to docker hub
  - docker push phhongphuc/multi-client
  - docker push phhongphuc/multi-nginx
  - docker push phhongphuc/multi-server
  - docker push phhongphuc/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'ap-southeast-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-ap-southeast-2-166685607634'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY